#ifndef COLOR_H
#define COLOR_H

#include <types.h>

extern const uint8 RGB_TABLE[140][3];

#define COLOR_COUNT                   140
#define COLOR_Pink                    0
#define COLOR_LightPink               1
#define COLOR_HotPink                 2
#define COLOR_DeepPink                3
#define COLOR_PaleVioletRed           4
#define COLOR_MediumVioletRed         5
#define COLOR_LightSalmon             6
#define COLOR_Salmon                  7
#define COLOR_DarkSalmon              8
#define COLOR_LightCoral              9
#define COLOR_IndianRed               10
#define COLOR_Crimson                 11
#define COLOR_FireBrick               12
#define COLOR_DarkRed                 13
#define COLOR_Red                     14
#define COLOR_OrangeRed               15
#define COLOR_Tomato                  16
#define COLOR_Coral                   17
#define COLOR_DarkOrange              18
#define COLOR_Orange                  19
#define COLOR_Gold                    20
#define COLOR_Yellow                  21
#define COLOR_LightYellow             22
#define COLOR_LemonChiffon            23
#define COLOR_LightGoldenrodYellow    24
#define COLOR_PapayaWhip              25
#define COLOR_Moccasin                26
#define COLOR_PeachPuff               27
#define COLOR_PaleGoldenrod           28
#define COLOR_Khaki                   29
#define COLOR_DarkKhaki               30
#define COLOR_Cornsilk                31
#define COLOR_BlanchedAlmond          32
#define COLOR_Bisque                  33
#define COLOR_NavajoWhite             34
#define COLOR_Wheat                   35
#define COLOR_BurlyWood               36
#define COLOR_Tan                     37
#define COLOR_RosyBrown               38
#define COLOR_SandyBrown              39
#define COLOR_Goldenrod               40
#define COLOR_DarkGoldenrod           41
#define COLOR_Peru                    42
#define COLOR_Chocolate               43
#define COLOR_SaddleBrown             44
#define COLOR_Sienna                  45
#define COLOR_Brown                   46
#define COLOR_Maroon                  47
#define COLOR_DarkOliveGreen          48
#define COLOR_Olive                   49
#define COLOR_OliveDrab               50
#define COLOR_YellowGreen             51
#define COLOR_LimeGreen               52
#define COLOR_Lime                    53
#define COLOR_LawnGreen               54
#define COLOR_Chartreuse              55
#define COLOR_GreenYellow             56
#define COLOR_SpringGreen             57
#define COLOR_MediumSpringGreen       58
#define COLOR_LightGreen              59
#define COLOR_PaleGreen               60
#define COLOR_DarkSeaGreen            61
#define COLOR_MediumSeaGreen          62
#define COLOR_SeaGreen                63
#define COLOR_ForestGreen             64
#define COLOR_Green                   65
#define COLOR_DarkGreen               66
#define COLOR_MediumAquamarine        67
#define COLOR_Aqua                    68
#define COLOR_Cyan                    69
#define COLOR_LightCyan               70
#define COLOR_PaleTurquoise           71
#define COLOR_Aquamarine              72
#define COLOR_Turquoise               73
#define COLOR_MediumTurquoise         74
#define COLOR_DarkTurquoise           75
#define COLOR_LightSeaGreen           76
#define COLOR_CadetBlue               77
#define COLOR_DarkCyan                78
#define COLOR_Teal                    79
#define COLOR_LightSteelBlue          80
#define COLOR_PowderBlue              81
#define COLOR_LightBlue               82
#define COLOR_SkyBlue                 83
#define COLOR_LightSkyBlue            84
#define COLOR_DeepSkyBlue             85
#define COLOR_DodgerBlue              86
#define COLOR_CornflowerBlue          87
#define COLOR_SteelBlue               88
#define COLOR_RoyalBlue               89
#define COLOR_Blue                    90
#define COLOR_MediumBlue              91
#define COLOR_DarkBlue                92
#define COLOR_Navy                    93
#define COLOR_MidnightBlue            94
#define COLOR_Lavender                95
#define COLOR_Thistle                 96
#define COLOR_Plum                    97
#define COLOR_Violet                  98
#define COLOR_Orchid                  99
#define COLOR_Fuchsia                 100
#define COLOR_Magenta                 101
#define COLOR_MediumOrchid            102
#define COLOR_MediumPurple            103
#define COLOR_BlueViolet              104
#define COLOR_DarkViolet              105
#define COLOR_DarkOrchid              106
#define COLOR_DarkMagenta             107
#define COLOR_Purple                  108
#define COLOR_Indigo                  109
#define COLOR_DarkSlateBlue           110
#define COLOR_SlateBlue               111
#define COLOR_MediumSlateBlue         112
#define COLOR_White                   113
#define COLOR_Snow                    114
#define COLOR_Honeydew                115
#define COLOR_MintCream               116
#define COLOR_Azure                   117
#define COLOR_AliceBlue               118
#define COLOR_GhostWhite              119
#define COLOR_WhiteSmoke              120
#define COLOR_Seashell                121
#define COLOR_Beige                   122
#define COLOR_OldLace                 123
#define COLOR_FloralWhite             124
#define COLOR_Ivory                   125
#define COLOR_AntiqueWhite            126
#define COLOR_Linen                   127
#define COLOR_LavenderBlush           128
#define COLOR_MistyRose               129
#define COLOR_Gainsboro               130
#define COLOR_LightGray               131
#define COLOR_Silver                  132
#define COLOR_DarkGray                133
#define COLOR_Gray                    134
#define COLOR_DimGray                 135
#define COLOR_LightSlateGray          136
#define COLOR_SlateGray               137
#define COLOR_DarkSlateGray           138
#define COLOR_Black                   139

#endif
